### PR TITLE
Register file named. Main index.js updated to match

### PR DESCRIPTION
**Pull request by kristin-takehara**
Register view in it's own file.

Main index.js update to match renamed Register view folder.

### CODE REVIEW

**Comment by kristin-takehara** [comment]
[SEPARATE login/register in to two DIFFERENT src - views](https://trello.com/c/uNpPqxnq/52-separate-login-register-in-to-two-different-src-views)

**Comment by kristin-takehara** [comment]
[SEPARATE login/register in to two DIFFERENT src - views](https://trello.com/c/uNpPqxnq/52-separate-login-register-in-to-two-different-src-views)

**Review by cozpon — APPROVED** [review]
LG2M

**Comment by kristin-takehara** [comment]
[Create Login/Register view](https://trello.com/c/N2KfabKx/48-create-login-register-view)

**Pull request merged**
